spring.application.name=orchestrator-service
server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/orchestrator_service_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

services.order.url=http://localhost:8081
services.payment.url=http://localhost:8082
services.inventory.url=http://localhost:8083
services.shipping.url=http://localhost:8084

management.endpoints.web.exposure.include=health,info,circuitbreakers,circuitbreakerevents
management.health.circuitbreakers.enabled=true

# Timeout de Feign por si un servicio no responde (dispara el CircuitBreaker)
spring.cloud.openfeign.client.config.default.connectTimeout=3000
spring.cloud.openfeign.client.config.default.readTimeout=3000